### ISSUE TITLE
when I try to start app server

### ISSUE THREAD

**Issue by arthurkulchenko** [arthurkulchenko/python_3rd_hw#1]
when I try to start app server by ```uwsgi --http :8000 --wsgi-file init.py```  in terminal

```Traceback (most recent call last):
  File "init.py", line 1, in <module>
    from response import generate_response
  File "./response.py", line 1, in <module>
    from view          import get_view_on
  File "./view.py", line 2, in <module>
    from template_engine import env
  File "./template_engine.py", line 4, in <module>
    loader=PackageLoader('init', 'templates'),
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/loaders.py", line 224, in __init__
    provider = get_provider(package_name)
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 348, in get_provider
    __import__(moduleOrReq)
  File "./init.py", line 1, in <module>
    from response import generate_response
ImportError: cannot import name generate_response
unable to load app 0 (mountpoint='') (callable not found or import error)
```

I see this.
P.S. mind the [branch](https://github.com/arthurkulchenko/python_3rd_hw/tree/add_template_engine) it is not the master

**Comment by arthurkulchenko** [comment]
after changing templating(jinja2) loader parametrs to 'loader=FileSystemLoader(os.getcwd() + '/lib/templates'),' all got better.
